/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cmpt305.lab3.gui.views;

import cmpt305.lab3.Settings.Avatar;
import java.awt.event.ActionListener;
import javax.swing.ComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author alex
 */
public class SettingsView extends javax.swing.JPanel{

	public void addConfirmButtonListener(ActionListener l){
		confirmButton.addActionListener(l);
	}

	public void removeConfirmButtonListener(ActionListener l){
		confirmButton.removeActionListener(l);
	}

	public void addResetCacheButtonListener(ActionListener l){
		resetCacheButton.addActionListener(l);
	}

	public void removeResetCacheButtonListener(ActionListener l){
		resetCacheButton.removeActionListener(l);
	}

	public void addGetApiKeyButtonListener(ActionListener l){
		getApiKeyButton.addActionListener(l);
	}

	public void removeGetApiKeyButtonListener(ActionListener l){
		getApiKeyButton.removeActionListener(l);
	}

	public String getAppId(){
		return this.appIDBox.getText();
	}

	public void setAppId(String key){
		this.appIDBox.setText(key);
	}

	public void displayUrlBox(String url){
		JOptionPane.showMessageDialog(this, "Get an api key at: " + url);
	}

	public void setAvatarModel(ComboBoxModel m, Avatar selected){
		avatarSize.setModel(m);
		avatarSize.setSelectedItem(selected);
	}

	public Avatar getAvatarSelection(){
		return (Avatar) avatarSize.getSelectedItem();
	}

	public int showConfirmDialog(String message, Object[] options){
		return JOptionPane.showOptionDialog(
				this,
				message,
				"Confirm",
				JOptionPane.YES_NO_OPTION,
				JOptionPane.WARNING_MESSAGE,
				null,
				options,
				options[1]);
	}

	/**
	 * Creates new form SettingsView
	 */
	public SettingsView(){
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        getApiKeyButton = new javax.swing.JButton();
        appIDBox = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        avatarSize = new javax.swing.JComboBox();
        confirmButton = new javax.swing.JButton();
        resetCacheButton = new javax.swing.JButton();

        jLabel1.setText("Steam API Key:");

        getApiKeyButton.setText("Get API Key");

        jLabel2.setText("Size of Steam User Avatars to Retrieve:");

        confirmButton.setText("Apply Changes");

        resetCacheButton.setBackground(new java.awt.Color(232, 76, 76));
        resetCacheButton.setText("RESET CACHE");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(resetCacheButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(getApiKeyButton))
                    .addComponent(appIDBox, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(avatarSize, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(confirmButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(getApiKeyButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(appIDBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(avatarSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(confirmButton)
                .addGap(18, 18, 18)
                .addComponent(resetCacheButton)
                .addContainerGap(139, Short.MAX_VALUE))
        );

        add(jPanel2);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField appIDBox;
    private javax.swing.JComboBox avatarSize;
    private javax.swing.JButton confirmButton;
    private javax.swing.JButton getApiKeyButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton resetCacheButton;
    // End of variables declaration//GEN-END:variables
}
